---
title: "Using Corpora in Social Science Research (UCSSR)"
subtitle: 'Best Slides Ever!'
author: "Andreas Blaette"
date: "8. August 2018"
output:
  slidy_presentation:
    footer: Copyright (c) 2018, Andreas Blaette
  beamer_presentation: default
  ioslides_presentation: default
editor_options: 
  chunk_output_type: console
---

<style>
.level6 { padding: 0em !important; width: 100%; height: 100%; }
</style>

--- 

Wir laden ein paar Bibliothken ... 

```{r}
library(polmineR.graph)
library(polmineR)
use("GermaParl")
```

----

Denn wir wollen uns die Reden von Angela Merkel in 2008 unter die Lupe nehmen.

```{r}
merkel2008 <- partition(
  "GERMAPARL",
  speaker = "Angela Merkel", year = 2008, interjection = FALSE,
  p_attribute = "word"
)
```

Allerdings gibt es ein paar Worte, die nicht so interessant sind.

```{r}
terms_to_drop <- c(
  polmineR::punctuation,
  unlist(noise(p_attributes(merkel2008, p_attribute = "word")))
)
```


----

Jetzt aber kommt die algorithmische Analyse!

```{r}
Merkel <- Cooccurrences$new(
  partition = merkel2008, p_attribute = "word", window = 5L,
  drop = terms_to_drop
)
Merkel$count()
Merkel$trim(action = "drop", by.id = TRUE)
Merkel$maths()
```

Was wir dann wieder ein bisschen eindampfen.

```{r}
Merkel$dt <- Merkel$dt[1:250]
```

----

Und so können wir daraus ein dreidimensionales Widget machen.

```{r}
G <- Merkel$as.igraph()
G <- addCoordinates(G, layout = "kamada.kawai", dim = 3)
G <- addCommunities(G)
G <- rescale(G, -250, 250)

T <- three(G, type = "base", raycaster = TRUE)
```

Auf der folgenden Seite ... Maus bewegen, Maustaste drücken etc. 

----

```{r, echo = FALSE}
T
```